modLoader="javafml"
loaderVersion="[40,)"
license="GNU GPLv3"
[[mods]]
modId="experimentalreactors"
version="${file.jarVersion}" #mandatory
displayName="Experimental Reactors" #mandatory
logoFile="" #optional
credits="Thanks for this example mod goes to Java"
authors="QuantumZizo" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Safely test reactors from a variety of mods in a creative setting, guaranteed no explosions!"
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.experimentalreactors]] #optional
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.experimentalreactors]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
